---
# Start of tasks

- name: Django app | Source code | Make sure directory exists
  tags: [django-app-code, django-initial]
  file:
    path: "{{ django_root }}"
    state: directory

- name: Django app | Source code | Push code
  tags: [django-app-code]
  when: django_push_mode == "sync"
  synchronize:
    src: "{{ django_local_repo_root }}"
    dest: "{{ django_root }}"
  notify:
    - python code updated

- name: Django app | Dependencies | Make sure pip is installed
  tags: [django-dependencies, django-initial]
  yum:  # Use yum for Red Hat
    name: python3-pip  # Updated to python3-pip
    state: present

- name: Django app | Dependencies | Custom Pip requirements
  tags: [django-dependencies]
  pip:
    requirements: "{{ django_pip_dependencies }}"
  notify:
    - python code updated

- name: Django app | Settings | Upload settings template
  tags: [django-settings]
  template:
    src: templates/django_settings.py.j2
    dest: "{{ django_app_root }}/{{ django_project_module }}/settings.py"
  notify:
    - python code updated

- name: Django app | Collect static assets
  tags: [django-static]
  django_manage:
    app_path: "{{ django_app_root }}"
    command: "collectstatic {{ django_static_collection_args | default('') }}"

